sudo: required
services:
  - docker
before_install:
  - docker build -t villecode/react -f Dockerfile.dev .

script:
  - docker run -e CI=true villecode/react npm run test

deplay:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-064560329534"
  bucket_path: "docker"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
